document.writeln("<!Doctype html>");
document.writeln("<html lang=\'zh\'>");
document.writeln("  <head>");
document.writeln("	<meta charset=\'UTF-8\'>");
document.writeln("	<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("	<link rel=\'stylesheet\' type=\'text/css\' href=\'../css/1.css\'>");
document.writeln("	<link href=\'//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\' rel=\'stylesheet\'>");
document.writeln("  </head>");
document.writeln("  <body>");
document.writeln("	<div id=\'cem\'></div>");
document.writeln("	<button id=\'top7\' class=\'top7\'></button>");
document.writeln("	<nav id=\'top6\' class=\'top6\'>");
document.writeln("	  <div class=\'top5\'>");
document.writeln("	    <h2 class=\'top4\'>大妖怪张淮汐</h2>");
document.writeln("	  </div>");
document.writeln("	  <ul class=\'top3s\'>");

document.writeln("	    <li class=\'top3\'>");
document.writeln("	      <a class=\'top2\' href=\'/\'>");
document.writeln("	        <span class=\'top1\'><i class=\'fa fa-home\'></i> 首页</span>");
document.writeln("	      </a>");
document.writeln("	    </li>");
document.writeln("	    <li class=\'top3\'>");
document.writeln("	      <a class=\'top2\' href=\'/html/link.html\'>");
document.writeln("	        <span class=\'top1\'><i class=\'fa fa-home\'></i> 链接</span>");
document.writeln("	      </a>");
document.writeln("	    </li>");
document.writeln("	    <li class=\'top3\'>");
document.writeln("	      <a class=\'top2\' href=\'/html/call.html\'>");
document.writeln("	        <span class=\'top1\'><i class=\'fa fa-home\'></i> 联系方式</span>");
document.writeln("	      </a>");
document.writeln("	    </li>");

document.writeln("	  </ul>");
document.writeln("	</nav>");
document.writeln("	<header id=\'header\'>");
document.writeln("	  <div id=\'head-img\'>");
document.writeln("		<a>");
document.writeln("		  <img src=\'http://q1.qlogo.cn/g?b=qq&nk=3317229064&s=640\'></a>");
document.writeln("	  </div>");
document.writeln("	  <div id=\'head-text\'>");
document.writeln("		<a class=\'headtext\'>大妖怪张淮汐</a>");
document.writeln("	  </div>");
document.writeln("	  <div>");
document.writeln("		<div class=\'tanwen\'><p id=\'hitokoto\'>..一言获取中..</p></div>");
document.writeln("	  </div>");
document.writeln("    </header>");
document.writeln("<script src=\'../js/1.js\'></script>");
document.writeln("	<script>var menu = new Menu;</script>");
document.writeln("  </body>");
document.writeln("</html>");
